export let objectfit1 = `<img src="./assets/images/media/media-28.jpg" class="object-fit-contain border rounded" alt="...">`,
objectfit2 = `<img src="./assets/images/media/media-28.jpg" class="object-fit-cover border rounded" alt="...">`,
objectfit3 = ` <img src="./assets/images/media/media-28.jpg" class="object-fit-fill border rounded" alt="...">`,
objectfit4 = ` <img src="./assets/images/media/media-28.jpg" class="object-fit-scale border rounded" alt="...">`,
objectfit5 = `<img src="./assets/images/media/media-28.jpg" class="object-fit-none border rounded" alt="...">`,
objectfit6 = `<img src="./assets/images/media/media-28.jpg" class="object-fit-sm-contain border rounded" alt="...">`,
objectfit7 = `<img src="./assets/images/media/media-28.jpg" class="object-fit-md-contain border rounded" alt="...">`,
objectfit8 = `<img src="./assets/images/media/media-28.jpg" class="object-fit-lg-contain border rounded" alt="...">`,
objectfit9 = `<img src="./assets/images/media/media-28.jpg" class="object-fit-xl-contain border rounded" alt="...">`,
objectfit10 = `<img src="./assets/images/media/media-28.jpg" class="object-fit-xxl-contain border rounded" alt="...">`,
objectfit11 = `<video src="./assets/video/1.mp4" class="object-fit-contain rounded border" autoplay loop muted></video>`,
objectfit12 = `<video src="./assets/video/1.mp4" class="object-fit-cover rounded border" autoplay loop muted></video>`,
objectfit13 = `<video src="./assets/video/1.mp4" class="object-fit-fill rounded border" autoplay loop muted></video>`,
objectfit14 = `<video src="./assets/video/1.mp4" class="object-fit-scale rounded border" autoplay loop muted></video>`,
objectfit15 = `<video src="./assets/video/1.mp4" class="object-fit-none rounded border" autoplay loop muted></video>`;
